----liquibase formatted sql
----changeset mlatalska:3
--
--INSERT INTO Company (company_id,company_name, adress, nip)
--VALUES (1,'Randstad Polska', 'Al.Jerozolimskie 137','1231231231');
--
--INSERT INTO Company (company_id,company_name, adress, nip)
--VALUES (2,'3M Wroclaw', 'Al.Klimkowka 21','9879879871');
--
----changeset mlatalska:4
--
--INSERT INTO Invoice (invoice_number, seller_id, buyer_id, bank_account_number, comments, date_of_issue, date_of_sale, date_of_payment, payment_method, date_of_created)
--VALUES ('02/2021', 1, 2, '123123123','Dobre te donaty', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'TRANSFER',CURRENT_TIMESTAMP);
--
----changeset mlatalska:5
--INSERT INTO Invoice_items (invoice_id, name, unit,quantity,vat_rate,net_price,net_value,gross_value)
--VALUES (1, 'Kasza manna', 'SZT',2.0, 'RATE_23_PERCENTS',2,4,4.92);
--
